### ISSUE TITLE
Adding community-contributed examples to docs or a github repo

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-topics#39] opened 2021-08-17 17:28 UTC
### Summary

This idea came up in the [Documentation Working group meeting](https://github.com/ansible/community/issues/579#issuecomment-896271973). Based on the docs survey from the beginning of this year, our readers are looking for more examples.

One specific area mentioned was more and better templating examples. So the idea came about that maybe we can create an area for community-contributed examples to expand on our existing documentation. This could either be on docs.ansible.com/ansible, or within a github repo. The docsite would in theory be more 'findable', but we wanted to open this up to community discussion to see if it's something people would want to contribute to, and how best to make this easy and yet verifiable that the examples work. 

This is the docs survey feedback for the specific template example request - https://github.com/ansible/ansible/issues/75507

**Comment by Andersson007** [comment] 2021-08-18 07:20
A random brainstorming idea:
- we could create a repo called say `community-examples` with CI configured or we could create a directory called, say, `community-examples` in [community-docs](https://github.com/ansible/community-docs) (there are some contributor documents in the root. We could move them to another directory)
- set up CI there + a test target
- if a contributor add an example, they have to add integration tests that reproduce the example (add a dedicated file and include it in `tasks/main.yml`) checking the output with `assert` or something

Later on, provided that there are enough examples, if we decide to have them somewhere on `docs.ansible.com`, we could
1) move pages to the docsite
2) if new examples appear, they should be tested in that repo first (or we could move the test target to `ansible/ansible`)
3) if tests pass, we'll add them to the docsite

**Comment by samccann** [comment] 2021-11-15 18:49
My thought is to go with `community-examples` because it emphasizes where these come from. Some of them may not be the 'best' way to solve a problem, but so long as they pass CI, we can still give them a home there.  I'll try to revive this discussion in the DaWGs meeting this week.

**Comment by samccann** [comment] 2021-11-16 16:58
We discussed this at the DaWGs meeting and voted to use `community-examples` for the repo name, and probably put the template examples under a directory in case we decide to add more categories of examples in the future.

**Comment by gundalow** [comment] 2021-11-24 11:25
> My thought is to go with `community-examples` because it emphasizes where these come from. Some of them may not be the 'best' way to solve a problem, but so long as they pass CI, we can still give them a home there. I'll try to revive this discussion in the DaWGs meeting this week.


+1

We should also define the directory structure so: 
* Easy for people to find
* Allows CI testing only if that specific example changes

**Comment by Andersson007** [comment] 2021-11-25 08:39
How about the following workflow?
I'll create a repository `ansible-community/community-examples` with the following basic structure
(can be redefined later):
```
.
├── examples
│   └── core
│       └── example1.yml -> ../../tests/integration/targets/core/tasks/example1.yml
└── tests
    ├── integration
        └── targets
            └── core
                └── tasks
                    ├── example1.yml
                    └── main.yml

```
Where ``core`` is a directory which includes examples for pure core modules / plugins

The following will be described in detail in the repo's `README.md`.

When someone wants to add an example for a core module/plugin, they create a PR which:
1) Create a test file in the `core` target, say `tests/integration/targets/core/tasks/example2.yml` with comments, asserts, etc.
2) Import this file in `tests/integration/targets/core/tasks/main.yml`.
3) Create a symlink to `tests/integration/targets/core/tasks/example2.yml` in `examples/core`.

Then we'll set up GHA.

What do you think? If it sounds sensible, I could implement this.

**Comment by Andersson007** [comment] 2021-12-10 10:48
I created the [community-examples](https://github.com/ansible-community/community-examples/issues/2) repo.

The next step is to get real examples.
Is anyone interested in giving us a couple of examples worthwhile having on docs.ansible.come? Feel free to create an issue in https://github.com/ansible-community/community-examples

**Comment by samccann** [comment] 2021-12-21 16:21
@felixfontein @Andersson007 since this is being implemented (nice tag!) should we close the issue?

**Comment by felixfontein** [comment] 2021-12-21 21:11
Since there is a new tracking issue for this (https://github.com/ansible-community/community-examples/issues/2) I think we can close this one.

**Closed by felixfontein** 2021-12-21 21:11 UTC
Labels: being_implemented
