### ISSUE TITLE
[Vote ended on 2022-12-16] Removal from Ansible 9: cyberark.pas

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/community-topics#168] opened 2022-11-30 19:52 UTC
### Summary

I'm filing this issue in accordance with [Removal from Ansible § Collections not satisfying the Collection Requirements](https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst#id41).

On 27 October (over four weeks ago), I opened an issue (https://github.com/cyberark/ansible-security-automation-collection/issues/46) against cyberark.pas's repository reporting their violation of the release tagging requirements. There has been no acknowledgment of the issue, and it hasn't been resolved, so it's eligible for removal from Ansible 9.

Two SC members need to confirm that this collection is indeed violating the requirements. After that, I'll give about a week long grace period before starting a vote on whether we should remove this collection from Ansible 9.

**Comment by mariolenz** [comment] 2022-12-02 17:37
At the time of writing this comment I don't see they [tag their releases](https://github.com/cyberark/ansible-security-automation-collection/tags).

So I agree / confirm that this collection is indeed violating the requirements.

**Comment by gotmax23** [comment] 2022-12-08 18:29
I've started a vote: https://github.com/ansible-community/community-topics/discussions/172

**Comment by mariolenz** [comment] 2022-12-16 12:13
I counted votes: 
7 x +1 from SC (gotmax23 felixfontein russoz mariolenz briantist markuman ssbarnea)
2 x +1 from community (oraNod cybette)

Can someone from the Steering Committee confirm this?

**Comment by jtuttle** [comment] 2022-12-16 13:41
Hi there, I'm the manager of the CyberArk Community & Integrations team at CyberArk. We are responsible for most of the OSS repositories but unfortunately this one doesn't fall under our umbrella. This lapse has just been brought to my attention. I will try to get the appropriate person / team working on it ASAP. Sorry for the delay.

**Comment by jtuttle** [comment] 2022-12-16 18:12
Update: I reached out to the person that manages @cyberark-bizdev directly and he said he will try to address it in the next few days, which I reckon will be next week sometime since it's Friday. I'll be on vacation next week but will try to hop on at some point to make sure this has been resolved.

**Comment by felixfontein** [comment] 2022-12-17 17:05
> I counted votes: 7 x +1 from SC (gotmax23 felixfontein russoz mariolenz briantist markuman ssbarnea) 2 x +1 from community (oraNod cybette) _edit:_ 1 x -1 from community (szh)
> 
> Can someone from the Steering Committee confirm this?

I can confirm this count.

**Comment by felixfontein** [comment] 2022-12-17 17:08
We talked a bit (informally) on this on IRC/Matrix, and we (well, the folks involved in the discussion there) are not really sure how to proceed with this. While we're happy that there is now some reaction, it is really late, considering that https://github.com/cyberark/ansible-security-automation-collection/issues/46 was created almost two months ago, and an earlier issue (https://github.com/cyberark/ansible-security-automation-collection/issues/44) from May has not received any feedback so far. We'll probably discuss this again in January once most folks are back from possible vacations.

**Comment by gotmax23** [comment] 2022-12-18 06:28
Yeah, it's unfortunate that there was no response for two months and it only happened after we already agreed to remove the collection from the ansible package. I haven't announced the removal of this collection yet, but I guess we'll need another vote to keep this collection in the Ansible package if the issue is fixed. In any case, I tagged this for discussion in the next community meeting.

**Comment by mhyclak-silex** [comment] 2022-12-19 17:14
This topic was just brought to my attention. I can say that we're using essentially a fork of cyberark.pas for one of our customers due to the inattention the modules received. There were some helpful patches in the Issues on the github repo that we pulled in and incorporated that allowed us to continue working. I would have to investigate from a contractual/legal standpoint what (if anything) we can share back to the community, but one of my teammates wrote some tests around the module as well. It's a tough one to do since you need a full-blown implementation to validate. I'm not sure if I'll be able to participate in the next meeting, but at least wanted to drop this comment for consideration.

**Comment by felixfontein** [comment] 2023-01-04 20:09
We talked about this a bit at today's community meeting. We decided to wait a few more days (until ~mid January) to see what happens with the collection, and then potentially start another vote whether to delay / cancel the removal or not.

**Comment by jtuttle** [comment] 2023-01-04 22:00
@felixfontein Thanks, I'm still trying to get the folks in charge of this project to fix it.

**Comment by infamousjoeg** [comment] 2023-01-06 02:59
Sorry this took so long. I went ahead and added a tag and release to match the version in Galaxy for the collection: https://github.com/cyberark/ansible-security-automation-collection/tree/1.0.14

**Comment by mariolenz** [comment] 2023-01-26 08:41
Closing because we decided to cancel the removal process in #180.

**Closed by mariolenz** 2023-01-26 08:41 UTC
Labels: discussion_topic, collection_exclusion
