### ISSUE TITLE
[Vote ended on 2023-02-14] Unmaintained collection: `google.cloud`

### ISSUE THREAD

**Issue by nkakouros** [ansible-community/community-topics#105] opened 2022-05-25 11:08 UTC
### Summary

The [`google.cloud`](https://github.com/ansible-collections/google.cloud/) collection has been unmaintained for some time now, it has:

- had only two commits the past 6 months about trivial stuff,
- no release for almost 1.5 years,
- 90 open and completely unanswered issues
- 26 pull requests ignored
- does not support hundreds of APIs and operations for google cloud.

Also, ansible was removed from the magic modules repository because building it is no longer supported in that repo. That repo also had no ansible commits for a year.

The collection kind of works now, but it has several bugs.

If it gets removed, users will be left with the `community.google` collection which is very limited. 

Maintaining it may be tricky as, in the past, it was generated automatically by magic modules and maybe it should still be done that way.

**Comment by felixfontein** [comment] 2022-05-25 11:15
Thanks for creating this issue!

There are two (somewhat distinct) problems:
1. How to get a maintained collection for GCP?
2. Keep google.cloud in Ansible or not?

About 1 I can't say much, except point to [Brian's email](https://groups.google.com/d/msgid/ansible-project/CACVha7d%3D%2BUBNX12gcC21r2g%2Ba79Mtt1%2BCRP_eH9dbQWC%2BnEYww%40mail.gmail.com) that the collection is owned by Google, so it's their decision what to do with google.cloud. (Anyone else has to think of Google Feed Reader?)

About 2: I think google.cloud qualifies as an unmaintained collection, so it should be removed from Ansible as described here: https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst#unmaintained-collections While this means that users who install Ansible from PyPi (or equivalent OS packages) no longer can directly access that collection, they can still manually install google.cloud (`ansible-galaxy collection install google.cloud`). So removing it doesn't make it impossible to still use it.

**Comment by felixfontein** [comment] 2022-05-25 11:16
CC @rambleraptor who has been pretty active on the google.cloud collection for a long time.

**Comment by felixfontein** [comment] 2022-06-01 20:04
Let's keep this open for a few more days, and if nobody is against that, I'll start the process as described [here](https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst#unmaintained-collections) by announcing that this collection seems unmaintained in The Bullhorn and in the collection's repository. Then roughtly a month later, assuming that the collection doesn't show any signs of being actively maintained again, we can start a vote for the Steering Committee. If then nothing happens again, the collection will be removed from Ansible 8.0.0 in roughly a year.

**Comment by toumorokoshi** [comment] 2022-06-06 23:22
Hello! I'm one of the current Google engineers working on magic-modules. rambleraptor no longer works at Google, but I can join in their place.

As @nkakouros has already said, we haven't been able to allocate time for the google.cloud ansible collection to get the attention it needs. 

Long term I think there's some effort we're working on that will improve our ability to support Ansible, but short-term I don't see a good option for first-party support. I know that's not a great answer, but I'm interested in finding the optimal (or least-worst) path forward.

It sounds like there's a community-maintained integration with GCP currently (community.google). Is it a better state to turn google.cloud over to a set of community contributors?

**Comment by felixfontein** [comment] 2022-06-07 19:25
@toumorokoshi thanks for your message, I really appreciate this! There is a [community.google collection](https://github.com/ansible-collections/community.google/), *but* it is effectively unmaintained as well. It contains some modules which were part of Ansible 2.9 that Google didn't want to have in the google.cloud collection (I guess because they were not automatically generated and predated magic-modules, but I never was involved in that). The main difference to google.cloud is that it is owned by the Ansible community team, so community contributions to it can be easily merged and new versions can be released. Unfortunately, there have been zero contributions so far, and also zero issues reported, which could also be a sign that nobody is using it (and maybe it isn't working at all).

(@nkakouros since you mentioned community.google: do you have any experience with it?)

**Comment by toumorokoshi** [comment] 2022-06-08 15:43
>  The main difference to google.cloud is that it is owned by the Ansible community team, so community contributions to it can be easily merged and new versions can be released.

yep! make sense.

To clarify I wasn't suggesting we use comomunity.google, but perhaps we can migrate google.cloud to something maintained by the community team? If the main issue is that the repo ownership is such that it's preventing people who want to maintain and be more active, I think we can move the ownership (or fork) to enable more activity.

I'm also happy to join in a community meeting or other medium if it'll help move things along quicker.

And sorry I'm not intricately familiar with the way this community operates, so if I'm misusing terminology or mischaracterizing a practice let me know.

**Comment by mariolenz** [comment] 2022-06-08 17:18
> If the main issue is that the repo ownership is such that it's preventing people who want to maintain and be more active, I think we can move the ownership (or fork) to enable more activity.

I'm afraid the main issue is that the collection is more or less unmaintained. Changing the ownership would allow the community to do this. But maybe nobody wants to, so the problem doesn't change: An unmaintained collection in Ansible.

I thought about moving the modules to `community.google` (they're both GPL3 as far as I can see, so this shouldn't be a problem) but, as @felixfontein pointed out, this collection is effectively unmaintained as well.

> And sorry I'm not intricately familiar with the way this community operates, so if I'm misusing terminology or mischaracterizing a practice let me know.

No reason to be sorry.

Just to make this clear: Removing `google.cloud` from Ansible doesn't mean people can't use it. They would just have to install it via `ansible-galaxy`. And it doesn't mean removing the repository, either. If Google starts to really maintain the collection some time in the future, we could add it again to the Ansible package.

**Comment by acozine** [comment] 2022-06-08 18:51
Draft announcement:

The Ansible community will remove the google.cloud collection from the Ansible package in Ansible 8.0.0.

Why is the google.cloud collection being removed?
The google.cloud collection is being removed in accordance with our [community guidelines for collections](https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst#unmaintained-collections), because it is unmaintained. The collection was last released in February, 2021, and the repo contains many open issues and pull requests with no responses at all. In addition, the functionality of the collection is outdated and minimal.

Can I still use the google.cloud collection?
Yes. The google.cloud collection is included in Ansible 6.x and will be included in Ansible 7.x with a deprecation warning. Starting with Ansible 8.0.0, you can still use the collection, but you must [install it from GitHub](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#installing-a-collection-from-a-git-repository).

Can I help maintain this collection and get it back into the Ansible package?
Yes! We are considering moving these modules into the community.google collection, but we need maintainers before we do that. If you can help, reach out to the Ansible community on Matrix or IRC for more information.

**Comment by felixfontein** [comment] 2022-06-08 19:13
I think this announcement can be used once the process is at step 5 ("Announce upcoming removal from Ansible Y").

**Comment by toumorokoshi** [comment] 2022-06-08 19:28
> Just to make this clear: Removing google.cloud from Ansible doesn't mean people can't use it. They would just have to install it via ansible-galaxy. And it doesn't mean removing the repository, either. If Google starts to really maintain the collection some time in the future, we could add it again to the Ansible package.

yes, I think that sounds fine. 

> I think this announcement can be used once the process is at step 5 ("Announce upcoming removal from Ansible Y").

I think the removal sounds good, and I agree the point that moving one unmaintained collection into another doesn't help. 

If someone is interested and you want some help moving the collection, let me know. Happy to be pinged on discussions around the google provider or google + ansible in general.

**Comment by nkakouros** [comment] 2022-06-08 22:13
There are two concerns about a potential move to community.google. 

The current "machine-generated" code has bugs. If these get solved through manual PRs, what will happen if magic modules start working again for ansible (via magic modules or whatever form the long-term effort @toumorokoshi mentions taks)? Will the fixes be undone? This will be bad for the users and if it is not catered for from the start, maintainers (i.e. people that have experience with google.cloud and who know a lot of its bugs) will be reluctant to spend time on work that has an expiration date. The same goes for new features/modules/plugins.

Would moving the collection also mean that a possible future for ansible in magic modules (or elsewhere) is sabotaged because the community will be anyway maintaining a google cloud collection?

**Comment by mariolenz** [comment] 2022-06-09 19:09
Proposal for the Bullhorn announcement (step 1):

It looks like the [google.cloud](https://github.com/ansible-collections/google.cloud) collection is effectively unmaintained. According to the current [community guidelines for collections](https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst#unmaintained-collections), we consider removing it in a future version of the Ansible community package. Please see [Unmaintained collection: google.cloud](https://github.com/ansible-community/community-topics/issues/105) for more information or to announce that you're interested in taking over the maintenance of `google.cloud`.

**Comment by felixfontein** [comment] 2022-06-09 19:23
I don't think it's possible to take over maintenance of google.cloud, but creating a community fork (be that in community.google or under another name). At least not without some coordination with Google first. So how about adjusting this to:

> It looks like the [google.cloud](https://github.com/ansible-collections/google.cloud) collection is effectively unmaintained. According to the current [community guidelines for collections](https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst#unmaintained-collections), we consider removing it in a future version of the Ansible community package. Please see [Unmaintained collection: google.cloud](https://github.com/ansible-community/community-topics/issues/105) for more information or to announce that you're interested in taking over the maintenance of (a fork of) `google.cloud`.

I would also expand a bit more on how the process works:

> At least one month after this announcement appears, the Ansible community engineering steering committee will vote on whether this collection is considered unmaintained and will be removed, or whether it will be kept. If it will be removed, this will happen earliest in Ansible 8.0.0. Please note that you can still manually install the collection with `ansible-galaxy collection install google.cloud` even when it has been removed from Ansible.

**Comment by felixfontein** [comment] 2022-06-09 19:29
> There are two concerns about a potential move to community.google.
> 
> The current "machine-generated" code has bugs. If these get solved through manual PRs, what will happen if magic modules start working again for ansible (via magic modules or whatever form the long-term effort @toumorokoshi mentions taks)? Will the fixes be undone? This will be bad for the users and if it is not catered for from the start, maintainers (i.e. people that have experience with google.cloud and who know a lot of its bugs) will be reluctant to spend time on work that has an expiration date. The same goes for new features/modules/plugins.

I think the only acceptable way is to reactivate Ansible support for magic modules (if that's not possible in magic modules itself, that needs to be forked as well). I have no idea how much work this is going to be - I guess it will be quite some amount of work. So this is IMO only a relalistic option if there are preferably multiple persons dedicating quite some time into this.

> Would moving the collection also mean that a possible future for ansible in magic modules (or elsewhere) is sabotaged because the community will be anyway maintaining a google cloud collection?

I personally don't think it makes sense to copy over anything from google.cloud without the help of magic modules (forked or not), basically for the reasons you are mentioning. (And also since it will be a **huge** manual effort to keep the modules updated.)

**Comment by mariolenz** [comment] 2022-06-10 05:09
@felixfontein Thanks! I think your changes / additions to my proposal sound great.

**Comment by felixfontein** [comment] 2022-06-15 18:17
I'd change the first sentence of the second paragraph of the issue tracker announcement to `At least one month after this announcement appears here and on [Bullhorn](https://github.com/ansible/community/wiki/News#the-bullhorn), ...`. Similar, the first sentence of the second paragraph of the Bullhorn announcement to `At least one month after this announcement appears here and in the collection's issue tracker, ...`.

**Comment by samccann** [comment] 2022-06-15 18:25
First paragraph should be `we will consider` (aka add `will`)

**Comment by mariolenz** [comment] 2022-06-15 19:31
FYI: ansible-collections/google.cloud#485

**Comment by felixfontein** [comment] 2022-07-20 17:53
The announcements have been there fore more than four weeks, so we could proceed with voting on this.

**Comment by mariolenz** [comment] 2022-07-20 19:10
I've opened a vote on this: #121

**Comment by felixfontein** [comment] 2022-07-20 20:14
@jamescassell (I'm writing here to avoid cluttering the discussion) the planned removal from Ansible 8 can easily be undone if that collection is maintained again. But yeah, it would be great if google.cloud would be maintained again and we wouldn't have to remove it, or announce removal in the first place :)

**Comment by felixfontein** [comment] 2022-08-03 08:21
I counted votes: 8 x +1 from SC (mariolenz felixfontein ssbarnea russoz Andersson007 briantist acozine cidrblock), 2 x 0 from SC (jamescassell markuman)

**Comment by Andersson007** [comment] 2022-08-03 08:23
I can confirm the [count](https://github.com/ansible-community/community-topics/issues/105#issuecomment-1203638253), SC 8 +1, 2 +0.

**Comment by felixfontein** [comment] 2022-08-03 09:43
In that case the proposal has been accepted, we consider `google.cloud` unmaintained and will announce to remove it from Ansible 8 in case its status doesn't change until then.

**Comment by mariolenz** [comment] 2022-08-06 14:39
Now that ansible-community/ansible-build-data#150 is merged, should we change the label to `implemented` and close this issue? Or should we keep this open until Ansible 8 is released without `google.cloud`? Or should we keep it open until Ansible 6.3 containing the deprecation is released?

**Comment by felixfontein** [comment] 2022-08-10 19:15
I'd suggest to keep this issue open until 8.0.0-b1 (feature freeze), so that discussions on finding new maintainers can take place here (without ending up in a closed issue).

**Comment by toumorokoshi** [comment] 2022-09-09 19:13
Hello! I'm using this issue as a place to have a discussion on the `google.cloud` provider in a little bit broader context than it's inclusion in the main Ansible package. Let me know if it's preferred to have a discussion or bring up updates in a different forum.

I've been discussing a bit internally on the best steps forward, and we've landed on the following proposal:

1. Permanently disconnecting the collection from magic-modules. The additional layer of magic-modules makes it difficult to accept community contributions that fix the code directly, and the magic-modules pipeline has a non-zero cost to maintain and add new resources.
3. Once (1) is complete, we can start reviewing and accepting PRs against the generated code (several of the outstanding PRs are modifying the resource directly).
4. In parallel I'm looking to have some set of reviewers who can keep up with PRs and issues. The volume hasn't been something unsustainable over the past year. This is also helped by (1) in that we can broaden the pool to those who know Ansible well, and no longer require Ansible + magic-modules knowledge.

My hope is that this moves the collection in a better direction, although I know it doesn't address all issues (e.g. *new* features of resources). 

For new resources we're looking at options that aren't concrete enough to share at the moment. 

Does anyone have thoughts or feedback?

**Comment by toumorokoshi** [comment] 2022-09-15 17:07
Hello,

If there's no strong pushback on this approach, we'll start implementing these changes this week. 

After the decoupling of magic-modules, I'll start a pass of existing GitHub issues and overall repo health.

**Comment by acozine** [comment] 2022-09-28 18:46
Thank you for figuring out a way forward @toumorokoshi! This sounds like a good plan for the collection.

**Comment by mariolenz** [comment] 2022-09-28 18:49
@toumorokoshi Your approach sounds reasonable. Great to see someone working on this collection again, thanks!

**Comment by mariolenz** [comment] 2022-11-26 17:10
@toumorokoshi Just FYI, `google.cloud` [has been removed from Ansible 8](https://github.com/ansible-community/ansible-build-data/commit/fa289d4812bfe4165e9fba498132b27e6e412c0f).

But as far as I understand, that's not necessarily final. If you release a new version of `google.cloud` during the next 5 months or so, we probably would re-consider our decision. At least, that's how I understand the process.

cc @felixfontein @gotmax23

**Comment by felixfontein** [comment] 2022-11-26 17:25
"has been" sounds strange for something that doesn't exist yet ;-) But yes, that's how it will happen, and if we decide that google.cloud is again actively maintained, we will reconsider this. @toumorokoshi please write here if you think we should reconsider the decision, then we'll discuss it.

**Comment by mariolenz** [comment] 2022-11-27 14:57
> "has been" sounds strange for something that doesn't exist yet ;-)

I know what you mean, but I'm quite sure both you and @toumorokoshi understand what I wanted to say ;-)

**Comment by toumorokoshi** [comment] 2022-11-28 20:03
> But as far as I understand, that's not necessarily final. If you release a new version of google.cloud during the next 5 months or so, we probably would re-consider our decision. At least, that's how I understand the process.

I'm targetting within the next month :) So definitely a a new version will exist, although stamping out all bugs is taking longer than I thought.

> 
"has been" sounds strange for something that doesn't exist yet ;-) But yes, that's how it will happen, and if we decide that google.cloud is again actively maintained, we will reconsider this. @toumorokoshi please write here if you think we should reconsider the decision, then we'll discuss it.

I would love to have it be reconsidered! But if the decision is being made within the next 5 months. I'll try to get some releases out as evidence that it could be re-incorporated and not leave a poor customer experience.

I'll ping on this thread when I feel like we're at a point when it's worth discussing. Does that sound okay?

**Comment by gotmax23** [comment] 2022-12-03 21:56
This has been implemented in https://github.com/ansible-community/ansible-build-data/commit/fa289d4812bfe4165e9fba498132b27e6e412c0f, but I'll leave this ticket open for further discussion

**Comment by toumorokoshi** [comment] 2023-01-03 18:21
The new version of the collection has shipped! [1.1.2](https://galaxy.ansible.com/google/cloud) contains a handful of bugfixes and a couple new features.

As mentioned I'll be reviewing PRs and fixing bugs as needed.

**Comment by Andersson007** [comment] 2023-01-04 08:35
@toumorokoshi great to hear, thanks for stepping up and taking care of the collection!

**Comment by felixfontein** [comment] 2023-01-04 20:07
We discussed this at today's community meeting, and decided to start a vote of re-including google.cloud to Ansible 8 once Ansible 7.2.0 is out (the next Ansible release that will contain the new google.cloud 1.1.2 release).

**Comment by mariolenz** [comment] 2023-01-04 20:21
> We discussed this at today's community meeting, and decided to start a vote of re-including google.cloud to Ansible 8 once Ansible 7.2.0 is out (the next Ansible release that will contain the new google.cloud 1.1.2 release).

@toumorokoshi If I forget to open a vote on re-including / canceling the removal google.cloud, please ping me :-)

**Comment by toumorokoshi** [comment] 2023-01-21 18:35
@mariolenz since you asked for a ping on the vote :) Did this vote happen, or is it planned?

**Comment by mariolenz** [comment] 2023-01-22 17:00
@toumorokoshi We wanted to wait until 7.2.0 has been released, which didn't happen yet. ETA is end of January / early February.

@felixfontein Do you think I should create just the vote, or also an issue similar to #180? We could re-use this issue for the vote, but it might be better to have a new one.

**Comment by felixfontein** [comment] 2023-01-22 17:16
@mariolenz reusing this issue should be fine IMO.

**Comment by toumorokoshi** [comment] 2023-01-23 18:57
> We wanted to wait until 7.2.0 has been released, which didn't happen yet. ETA is end of January / early February.

Got it! Thank you.

**Comment by mariolenz** [comment] 2023-02-01 12:47
Vote on cancelling the removal process happens in #195

**Comment by felixfontein** [comment] 2023-02-09 16:38
@ansible-community/steering-committee please do not forget to vote on https://github.com/ansible-community/community-topics/discussions/195, the vote ends **today** and does not have enough SC votes!

**Comment by mariolenz** [comment] 2023-02-14 08:31
I counted votes:

7 x +1 from SC (mariolenz briantist felixfontein Andersson007 acozine russoz ssbarnea)

2 x +1 from community (jillr cybette)

1 x neutral +0 from SC (gotmax23)

Can someone from the Steering Committee confirm?

**Comment by Andersson007** [comment] 2023-02-14 09:23
> I counted votes:
> 
> 7 x +1 from SC (mariolenz briantist felixfontein Andersson007 acozine russoz ssbarnea)
> 
> 2 x +1 from community (jillr cybette)
> 
> 1 x neutral +0 from SC (gotmax23)
> 
> Can someone from the Steering Committee confirm?

i've counted the same numbers

**Comment by mariolenz** [comment] 2023-02-14 10:29
Then it looks like the vote has been accepted and we will _keep_ `google.cloud` in Ansible 8.

I'll create a PR for ansible-build-data and a Bullhorn announcement later this day.

Thanks all!

**Comment by mariolenz** [comment] 2023-02-16 10:39
ansible-community/ansible-build-data#201

**Closed by mariolenz** 2023-02-16 10:39 UTC
Labels: implemented, collection_exclusion
