### ISSUE TITLE
[associated vote ended on 2023-11-08] Proposal: allow votes to be conducted in the forum

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-topics#273] opened 2023-09-20 18:31 UTC
### Summary

Right now the SC docs (https://docs.ansible.com/ansible/latest/community/steering/community_steering_committee.html#community-topics-workflow) explicitly say that votes have to happen here. The forum allows us to also vote (https://forum.ansible.com/t/lets-try-a-vote-in-the-sc-style/150/9), and it's a lot easier there.

I'd propose that we also allow having votes in the Ansible Forum.

@ansible-community/steering-committee what do you think? Does anyone have reservations?

**Comment by briantist** [comment] 2023-09-20 18:34
Aye, looking forward to moving past the GH-based votes and the various issues/discussions/PRs and their associated notifications

**Comment by leogallego** [comment] 2023-09-20 18:42
I would suggest setting a time-line and swapping votes to the forum directly as the proposal, having 2 places might be confusing, something like:

"starting on contributor summit (19th oct) votes for new topics will be created in the forum, and if there are ongoing community-topic votes, those will be kept in Github until finalized"

**Comment by acozine** [comment] 2023-09-20 18:45
+1 to moving votes to the forum, it's optimized for this kind of work

**Comment by felixfontein** [comment] 2023-09-20 18:46
I would keep community-topics as a backup for some time, in case voting in the forum breaks down unexpectedly. As @samccann suggested on Matrix, community-topics would only be used as a fallback, all new votes would be in the forum (if nothing bad happens).

**Comment by GregSutcliffe** [comment] 2023-09-25 10:13
Thanks for starting this @felixfontein! Clearly my non-SC vote is in favour :)

More usefully - two thoughts. First, if voting "breaks down" in some way on the new forum **please** tell me as soon as possible. There's a *lot* of possible configuration / automation we can do, and if that fails I can involve CDCK to help us too. I think we all want this to work (given what we have to deal with here) so *be as petty as you like* because I want this to be a lovely experience ;)

Second, if there's anything I can do to help one or more folks get comfortable with the tooling, again get in touch. I did some fairly [generic videos](https://forum.ansible.com/t/discourse-video-demos/102/3) which I can do more of, or do some writing somewhere, or whatever would help.

Finally, because I know someone will ask, I have already created a tool to list all the open polls on the site ([here](https://connect.eng.ansible.com/open_polls/open_polls.html) and in the forum sidebar). You can search for polls using the native search but it returns closed polls, so I thought this would be better - and allows me to showcase linking up our forum with our data platform, which has *many* other uses ;)

**Comment by samccann** [comment] 2023-09-25 15:18
My non-SC vote is +1 to moving to the forum. It raises visibility to what's being discussed here.

**Comment by gotmax23** [comment] 2023-09-27 18:42
Proposal: Try out the forum for at least one vote and, if it goes well, all of October. I would like to have written documentation for the process and a `steering-committee` tag on the forum.

**Comment by cybette** [comment] 2023-09-28 09:13
+1 (non-SC)

**Comment by maxamillion** [comment] 2023-09-29 17:13
+1 ALL THINGS IN THE FORUM (non-SC)

**Comment by Andersson007** [comment] 2023-10-02 06:48
+1 to all SC-related undertakings in the forum ASAP

**Comment by Andersson007** [comment] 2023-10-04 06:50
> Proposal: Try out the forum for at least one vote and, if it goes well, all of October. I would like to have written documentation for the process and a `steering-committee` tag on the forum.

@gotmax23 yes, let's do it after the first vote.
By the way, let's move this topic to the forum and vote on moving votes right there:)

**Comment by Andersson007** [comment] 2023-10-04 07:45
I possible vote here can be:
```
Allow new Steering Committee topics to be created and related votes to be conducted in the forum within the trial period without changing the Steering Committee guidelines.
The trial period will start after the vote ends, provided that the decision is positive, and will end on November, 14, 2023.
Further topics and votes to happen in the forum will be possible only after a corresponding Steering Committee guidelines change.
```
Please don't vote right now:) It's just a vote wording proposal. I think if we give the vote a week, so the trial period will be roughly a month. Or we can make it longer, say, 2 month and vote on the SC policy change right there during the trial in case the majority is happy with it.
Ideas?

**Comment by felixfontein** [comment] 2023-10-04 10:14
Do I understand the proposal right that we'd need another vote here in November to really transition to the forum?

How about, changing that part, so that if we decide to not continue using the forum after the end of the trial period, we have to start a vote in community-topics before November 14th (and, say, after November 1st).

**Comment by Andersson007** [comment] 2023-10-04 10:54
@felixfontein i updated the [proposal](https://github.com/ansible-community/community-topics/issues/273#issuecomment-1746319357) PTAL (i'm personally OK with any changes, so feel free to copy-paste, update, and put your version in a comment)

**Comment by felixfontein** [comment] 2023-10-04 18:13
I would formulate it as follows:
```
Allow new Steering Committee topics to be created and
related votes to be conducted in the forum within the trial period
without changing the Steering Committee guidelines.

The trial period will start after the vote ends, provided that the decision is positive,
and will end on November, 14, 2023.
From then on, all votes and discussions will happen in the Forum.
If this is deemed unacceptable by any Steering Committee or community member,
a vote needs to be started to revert to github.com/ansible-community/community-topics
between November 1st and November 14th and has to be open for at least one week.
If that vote is accepted, voting will no longer be possible in the forum, but only here.

Please vote +1/-1
```
That way by default voting stays in the forum, except if we explicitly revert back here.

**Comment by felixfontein** [comment] 2023-10-04 18:59
Ok, we talked about this at today's meeting. My (somewhat subjective) interpretation is:

1. We first want a draft PR for updating the SC docs that explains how exactly the process will work in the forum.
    - It was suggested to first prepare a text most are happy with in a forum wiki post (more precisely, this one: https://forum.ansible.com/t/draft-for-sc-voting-process-on-the-forum/1410).
    - Once we are happy enough someone turns it into a PR.
2. Once the PR is ready, we start a vote.
    - All SC members must be pinged (on GH) for that vote.
4. If the vote is accepted, we will have a ~one month trial period in which we do votes only in the forum.
5. By default, after the end of the trial period we will continue discussing and voting in the forum. No further action is necessary for this.
6. If someone wants to **prevent** that we continue voting in the forum, they have to create a vote **here** (in community-topics) that the trial period should not be extended.
    - That vote must not be started before at least half of the trial period is over.
    - The vote must run for at least one week.
    - All SC members need to be pinged (on GH *and* in the forum) for that vote, to make sure everyone is aware of it.

Does this sound good?

**Comment by Andersson007** [comment] 2023-10-09 08:47
>Does this sound good?

@felixfontein , absolutely!

**Comment by felixfontein** [comment] 2023-10-25 18:52
We not have a **vote** in #279. Please vote :)

@ansible-community/steering-committee please note that this vote changes the way how votes work, so please take a look (and vote for or against it)!

**Comment by mariolenz** [comment] 2023-10-28 11:29
The proposal says:

> A steering committee member can tag the forum post with `community-meeting` to put it on the meeting agenda.

This tag was OK here, but it might be a little bit problematic in the forum where there are also other (sub-) communities active. It's a little bit ambiguous. Please see [this post](https://forum.ansible.com/t/what-to-rename-community-topics-to-as-a-forum-tag/135/24?u=mariolenz) from @GregSutcliffe about this. And possibly also join the discussion there ;-)

It would be great if we could agree on the tag(s) to use _before_ we transition things to the forum. Of course, we could change things in the future but somehow this feels only like the second-best solution.

**Comment by gotmax23** [comment] 2023-10-31 05:31
I'd prefer to continue the discussion here. The discussion and votes about moving our processes to the forum should not happen there until we have actually agreed to do so.

**Comment by Andersson007** [comment] 2023-10-31 06:49
Speaking about tags: this is a good point, though it's a detail and imo is not an obstacle to finish the vote and is not a reason to suspend it. Otherwise we'll never move:)

IMO
- `community-meeting` is fine as only SC forum group members will be allowed to apply it.
- `sc-meeting` is not fine as it is about the community.
- `community-wg-meeting`: can also work

**Comment by felixfontein** [comment] 2023-10-31 07:18
I'm fine with `community-wg-meeting` if that solves the problems.

**Comment by Andersson007** [comment] 2023-10-31 09:09
> I'm fine with `community-wg-meeting` if that solves the problems.

@mariolenz @gotmax23 if you're OK too, I would update the PR. FYI today after lunchtime and tomorrow all day i won't be available, so feel free to push to my PR and commit

**Comment by gotmax23** [comment] 2023-10-31 21:52
Would y'all be fine with changing it to `community-wg-meeting` and also extending the vote to Monday? I think we should extend the vote anyways, and if we're changing the proposal, we should at least give folks time to give it another look.

**Comment by gotmax23** [comment] 2023-10-31 21:53
Also, if we are using `community-wg-meeting`, I'd prefer not to have `community-meeting` used at all (even for something other than our meeting) to avoid confusion.

**Comment by felixfontein** [comment] 2023-11-01 11:58
> Would y'all be fine with changing it to `community-wg-meeting` and also extending the vote to Monday? I think we should extend the vote anyways, and if we're changing the proposal, we should at least give folks time to give it another look.

In that case, we should also adjust the dates in the vote to ~a week later.

**Comment by felixfontein** [comment] 2023-11-01 19:14
At today's meeting we discussed this, and decided as follows:
- change the `steering-committee` tag to `community-wg`;
- change the `community-meeting` tag to `community-wg-nextmtg`;
- extend the dates mentioned in the vote by one week;
- prolong the vote by one week.

We'll update the PR and the vote next, and then ping everyone who voted so far so they can reconsider their vote if they don't like these changes.

**Comment by felixfontein** [comment] 2023-11-08 19:58
I counted the following votes:

8 x +1 from SC members (gotmax23 acozine felixfontein briantist Andersson007 mariolenz gundalow russoz)
3 x +1 from community members (leogallego cybette samccann)

Could another SC member please count the votes? Thanks!

**Comment by gotmax23** [comment] 2023-11-08 20:12
I can confirm @felixfontein's vote count!

**Closed** 2023-11-08 20:25 UTC
Labels: discussion_topic

**Comment by felixfontein** [comment] 2023-11-08 20:38
A very first discussion in the forum: https://forum.ansible.com/t/stop-using-the-gh-com-ansible-community-meeting-agenda-for-the-community-wg-meeting/2243

**Comment by leogallego** [comment] 2023-11-08 20:43
Created `community-wg` as an open tag, and `community-wg-nextmtg` limited to SC + ACT in the Forum
