### ISSUE TITLE
[Vote ended on 2022-06-07] CLI program which prints the Ansible package's version

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#89] opened 2022-04-14 11:52 UTC
### Summary

This is a follow-up to #87. As @felixfontein pointed out:

> I think it would be worth integrating a small CLI program which prints this version, but the hard part is figuring out how to name it... Everything with prefix `ansible` is kind of reserved for the core team, and if we want to use something like `ansible-version` we should better ask for permission / coordinate that.

I agree that this would be useful. However, I would prefer something with `ansible` in the name. Even if we have to ask for permission / coordinate that.

How about `ansible-community` with a parameter `--version`? This would allow us to add more parameters when needed like (this is just a stupid example) `--about` without having to to bother the core team again.

Or `ansible-community-version` if we don't think we'll need more parameters.

Of course, we could turn it around:  `community-ansible` / `community-ansible-version`. But I like it better the other way.

Ideas?

**Comment by felixfontein** [comment] 2022-04-14 19:04
Hmm, `ansible-community --version` sounds good to me. Also `ansible-community` should be a safe name for a CLI program.

**Comment by Andersson007** [comment] 2022-04-22 09:55
i'm personally for more generic name like `ansible-community` with `--version`, SGTM

**Comment by mariolenz** [comment] 2022-05-06 05:47
Should I open a vote for this?

And how would we implement it? I thought about this. One way would be to add something like `src/antsibull/data/ansible-community.js2` and then let antsibull generate it:

```
#!/usr/bin/python
# coding: utf-8
# Author: Mario Lenz <m@riolenz.de>
# License: GPLv3+
# Copyright: Ansible Project, 2022

import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--version', action='version', version='ansible community version {{ version }}', help="show the version of the ansible community package")
    args = parser.parse_args()

if __name__ == '__main__':
    main()
```

What do you think?

**Comment by apple4ever** [comment] 2022-05-27 21:00
YES PLEASE. I love this proposal, and I had thought about submitted it, but glad I was beaten to it. 

I would prefer if it showed up under any of the `--version`, like `ansible --version` or `ansible-playbook --version`, but at the very least having `ansible-community --version` would be great (and maybe then the others could output it if it exists).

**Comment by bmbufalo** [comment] 2022-05-28 17:19
Keeping the version information in a single location, such as under `ansible --version` would be preferred IMO, but any way we can get this information would also be helpful!

**Comment by felixfontein** [comment] 2022-05-28 19:22
Including that information in `ansible --version` or `ansible-playbook --version` is not possible since the core team does not want to have it there. So it's either a separate program (like `ansible-community --version`), or it's nowhere at all.

**Comment by mariolenz** [comment] 2022-06-01 19:28
ansible-community/antsibull#429

**Comment by felixfontein** [comment] 2022-06-01 20:08
I edited the post above since I noticed that [there is no 6.0.0b3 release](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/COLLECTIONS_6.rst#release-schedule). The release next week is 6.0.0rc1. This is a bit more tight than I thought, and if something goes wrong we'll definitely need another release candidate.

**Comment by acozine** [comment] 2022-06-06 17:42
+1 to offering users a way to tell which package version, as well as which core version, is installed on their machines.

**Comment by Andersson007** [comment] 2022-06-07 10:55
> I counted 7 steering committee +1 votes (mariolenz felixfontein russoz markuman briantist Andersson007 acozine) and 3 community +1 votes (cybette samccann Ompragash)

I can confirm too:)

**Comment by felixfontein** [comment] 2022-06-07 10:55
Awesome, thanks everyone! Then this is concluded :)

**Comment by felixfontein** [comment] 2022-06-07 19:12
The latest Ansible 6.0.0rc1 release contains the CLI program. Just tested it :) I'm going to close this issue.

**Closed by felixfontein** 2022-06-07 19:12 UTC
Labels: discussion_topic
